namespace BenMcLean.Wolf3D.Simulator;

/// <summary>
/// Interface for events generated by the simulator.
/// Events describe what happened during simulation and when.
/// </summary>
public interface ISimulationEvent
{
	/// <summary>
	/// When this event occurred (in seconds since simulation start).
	/// </summary>
	double Timestamp { get; }
}

/// <summary>
/// A door started opening.
/// Triggered in WL_ACT1.C:DoorOpening when position==0
/// </summary>
public struct DoorOpeningEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }
	public required ushort TileX { get; init; }
	public required ushort TileY { get; init; }
}

/// <summary>
/// A door finished opening and is now fully open.
/// Triggered in WL_ACT1.C:DoorOpening when position>=0xFFFF
/// </summary>
public struct DoorOpenedEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }
	public required ushort TileX { get; init; }
	public required ushort TileY { get; init; }
}

/// <summary>
/// A door's position changed during opening or closing animation.
/// Triggered every tic in WL_ACT1.C:DoorOpening and DoorClosing when position changes.
/// </summary>
public struct DoorPositionChangedEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }
	public required ushort TileX { get; init; }
	public required ushort TileY { get; init; }
	public required ushort Position { get; init; }  // Current position (0=closed, 0xFFFF=open)
	public required DoorAction Action { get; init; }  // Opening or Closing
}

/// <summary>
/// A door started closing.
/// Triggered in WL_ACT1.C:CloseDoor
/// </summary>
public struct DoorClosingEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }
	public required ushort TileX { get; init; }
	public required ushort TileY { get; init; }
}

/// <summary>
/// A door finished closing and is now fully closed.
/// Triggered in WL_ACT1.C:DoorClosing when position<=0
/// </summary>
public struct DoorClosedEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }
	public required ushort TileX { get; init; }
	public required ushort TileY { get; init; }
}

/// <summary>
/// Player tried to open a locked door without the required key.
/// Triggered in WL_ACT1.C:OperateDoor when key check fails (plays NOWAYSND)
/// </summary>
public struct DoorLockedEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }

	// WL_DEF.H:doorstruct:lock (byte in original)
	// Extended to string for modding: "gold key", "silver key", etc.
	public required string RequiredKey { get; init; }
}

/// <summary>
/// A door was blocked from closing (actor or player in the way).
/// Would be triggered in WL_ACT1.C:DoorClosing when blocking check fails
/// </summary>
public struct DoorBlockedEvent : ISimulationEvent
{
	public required double Timestamp { get; init; }
	public required ushort DoorIndex { get; init; }
	public required ushort TileX { get; init; }
	public required ushort TileY { get; init; }
}
